"""Add owner_id to Note

Revision ID: 920ece1a3494
Revises: 4ed05cd04993
Create Date: 2025-10-14 14:xx:xx.xxxxxx

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920ece1a3494'
down_revision = '4ed05cd04993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add owner_id as nullable first
    op.add_column('note', sa.Column('owner_id', sa.Integer(), nullable=True))
    
    # Step 2: Set a default value for existing rows (use the first user's id)
    # This assumes you have at least one user in the database
    op.execute('UPDATE note SET owner_id = (SELECT id FROM user LIMIT 1) WHERE owner_id IS NULL')
    
    # Step 3: Make owner_id NOT NULL
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('owner_id', nullable=False)
        batch_op.create_foreign_key('fk_note_owner_id', 'user', ['owner_id'], ['id'])
    
    # Add other columns
    op.add_column('note', sa.Column('share_token', sa.String(), nullable=True))
    
    # Create index for share_token
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index('ix_note_share_token', ['share_token'], unique=False)
    
    # Remove old author column if it exists
    try:
        with op.batch_alter_table('note', schema=None) as batch_op:
            batch_op.drop_column('author')
    except:
        pass  # Column might not exist
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add author column back
    op.add_column('note', sa.Column('author', sa.VARCHAR(), nullable=True))
    
    # Drop the index
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index('ix_note_share_token')
    
    # Drop share_token column
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('share_token')
    
    # Drop foreign key and owner_id column
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint('fk_note_owner_id', type_='foreignkey')
        batch_op.drop_column('owner_id')
    
    # ### end Alembic commands ###